# Generated by Django 3.1.1 on 2020-09-27 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.EmailField(max_length=255, unique=True, verbose_name='E-Posta')),
                ('self_description', models.TextField(blank=True, null=True, verbose_name='Açıklama')),
                ('first_name', models.CharField(max_length=30, verbose_name='Ad')),
                ('last_name', models.CharField(max_length=30, verbose_name='Soyad')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('is_admin', models.BooleanField(default=False, verbose_name='Admin')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('registered_date', models.DateTimeField(auto_now_add=True, verbose_name='Kayıt Tarihi')),
            ],
            options={
                'verbose_name': 'Kullanıcı',
                'verbose_name_plural': 'Kullanıcılar',
            },
        ),
    ]
